### ISSUE TITLE
Bugs Epic

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#203]
Header
- [x] https://github.com/iFixit/react-commerce/issues/202
- [x] https://github.com/iFixit/react-commerce/issues/189
- [x] https://github.com/iFixit/react-commerce/issues/205
- [x] https://github.com/iFixit/react-commerce/issues/216

Related to the Algolia Index
- [x] https://github.com/iFixit/react-commerce/issues/195
- [x] https://github.com/iFixit/react-commerce/issues/193
- [x] https://github.com/iFixit/react-commerce/issues/191
- [x] https://github.com/iFixit/react-commerce/issues/187
- [x] https://github.com/iFixit/react-commerce/issues/122
- [x] https://github.com/iFixit/react-commerce/issues/219

Mobile Experience
- [x] https://github.com/iFixit/react-commerce/issues/201
- [x] https://github.com/iFixit/react-commerce/issues/197
- [x] https://github.com/iFixit/react-commerce/issues/196
- [x] https://github.com/iFixit/react-commerce/issues/206

Misc UI bugs:
- [x] https://github.com/iFixit/react-commerce/issues/198
- [x] https://github.com/iFixit/react-commerce/issues/188
- [x] https://github.com/ifixit/react-commerce/issues/175
- [x] https://github.com/iFixit/react-commerce/issues/213
- [x] iFixit/ifixit#42374

Accessibility:
- [x]  https://github.com/iFixit/react-commerce/issues/194
