### ISSUE TITLE
Add "Popular Fix kits" section into parts collection page

### ISSUE THREAD

**Issue by dhmacs** [iFixit/react-commerce#29]
Add a section to the Parts collection page that contains popular fix kits as shown below:

![Screen Shot 2021-06-23 at 16 18 38](https://user-images.githubusercontent.com/4640135/123113223-acf91d00-d43e-11eb-9c88-a6188578279f.png)

## Todos

- [x] Add graphql codegen config for Shopify storefront
- [x] Add "FeaturedCollection" section component to Strapi collection
- [x] Add storefront credentials to strapi Store model (different regions use different Shopify stores, hence they have different credentials)
- [x] Fetch data from Algolia
- [x] Create featured collection section react component

**Comment by dhmacs** [comment]
@sterlinghirsh I have 2 possible implementation for this:

1. Use a Shopify collection
2. Fetch section title and description from Strapi + fetch products from Algolia

Since this looks like a manually curated list of products I think we should go with solution 1. 
What do you think?

**Comment by sterlinghirsh** [comment]
That's fine with me
