### ISSUE TITLE
Product page: Add tests

### ISSUE THREAD

**Issue by batbattur** [iFixit/react-commerce#452]
Here is a list of desired/potential tests we would like to add to the new product page when it's ready to be tested.
Please feel free to add or edit the list. 

- [x] https://github.com/iFixit/react-commerce/issues/1029

- [x] https://github.com/ifixit/react-commerce/issues/1043
   - [x] [Make sure the product title, item code, and price are visible at all times.](https://github.com/iFixit/react-commerce/pull/1050)
   - [x] [Login as pro user, and check that the price matches the pro user's tier.](https://github.com/iFixit/react-commerce/pull/1049)
- [x] https://github.com/ifixit/react-commerce/issues/1044

- [x] `Add to cart` button 
	- [x] #843 
	- [x] ifixit/ifixit#45153
	- [x] https://github.com/iFixit/react-commerce/issues/1168 - `Playwright`

- [x] https://github.com/iFixit/react-commerce/issues/1141

- [x] https://github.com/iFixit/react-commerce/issues/1132

- [x] https://github.com/ifixit/react-commerce/issues/1042 -`Jest` test

- [x] https://github.com/ifixit/react-commerce/issues/1045 https://github.com/iFixit/react-commerce/pull/1051

- [x] https://github.com/iFixit/react-commerce/issues/1142

- [x] https://github.com/iFixit/react-commerce/issues/1205 - `Playwright` test

- [x] https://github.com/iFixit/react-commerce/issues/1143

- [x] https://github.com/iFixit/react-commerce/issues/1144

- [x] https://github.com/iFixit/react-commerce/issues/1145

- [x] https://github.com/iFixit/react-commerce/issues/1165 - `Jest` test

- [x]  https://github.com/iFixit/react-commerce/issues/1200 - `Playwright` test

- [x] https://github.com/iFixit/react-commerce/issues/1166 - `Jest` test

- [x] https://github.com/iFixit/react-commerce/issues/1167 - `Jest` test

- [x] Reviews - Both `Jest` and `Playwright`
	- [x] https://github.com/iFixit/react-commerce/issues/1146
	- [x] https://github.com/iFixit/react-commerce/issues/1201

- [x] https://github.com/iFixit/react-commerce/issues/1202 - `Playwright` 

- [x] https://github.com/iFixit/react-commerce/issues/1203 - `Playwright?`

- [x] https://github.com/iFixit/react-commerce/issues/1164 - `Jest`

- [x] https://github.com/iFixit/react-commerce/issues/1163 - `Jest`

- [x] https://github.com/iFixit/react-commerce/issues/1204 - `Playwright`
 
<hr>

For the following sections, I'm not sure if these features will be added in the new store
- International buybox button.
- URL redirect for incorrect product names. For example, https://www.ifixit.com/Store/INVALID_NAME/IF145-299 redirects to https://www.ifixit.com/Store/Tools/Mako-Driver-Kit--64-Precision-Bits/IF145-299?o=4

cc: @mlahargou

**Comment by batbattur** [comment]
All tests got implemented 🎉 

@iFixit/qae we can close this Epic?

**Comment by ardelato** [comment]
Yes sir!
