### ISSUE TITLE
Finish header/footer

### ISSUE THREAD

**Issue by erinemay** [iFixit/react-commerce#653]
Bringing all the polish/finish header/footer issues into one place

Header
- [x] https://github.com/iFixit/react-commerce/issues/256 (admins only)
- [x] https://github.com/iFixit/react-commerce/issues/151
- [ ] Implement notifications (unclear if we still want notifications in the header since they're also in the user dropdown menu)

Footer
- [x] https://github.com/iFixit/react-commerce/issues/652

**Comment by dhmacs** [comment]
> Implement notifications (unclear if we still want notifications in the header since they're also in the user dropdown menu)

Do we need to have a separate item for notifications? I recall that we wanted to keep them in the user dropdown to avoid CLS from having a bell icon that is only present if there's a logged in user. Are you ok with just keeping notifications inside the user menu? If so, we can close this issue.

cc @sterlinghirsh @erinemay

**Comment by sterlinghirsh** [comment]
I'm ok with notifications in the user menu though I think we'll want to list the notifications and/or have an indicator when there are unread notifications. We may want to rework the api a little bit to make that easier.

**Comment by dhmacs** [comment]
Closing this in favor of https://github.com/iFixit/ifixit/issues/50434
